### ISSUE TITLE
Provide documentation on changing public facing application ports

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#262]

**Comment by mpigram** [comment]
In order to change the public facing application ports, you will need to edit the following values within the ```values.yaml``` files in the following charts

- Adaptation
- Administration
- Filedrop

Adaptation - values.yaml
```yaml
lbService:
  dnsname: icap-client-main
  nontlsport: 1344 << change port number
  tlsport: 1345 << change port number
```

Administration - values.yaml
```yaml
  deployment:
  ingress:
    name: icap-management-ui-ingress
    port: 80 << change this port number
    host: management-ui-develop.uksouth.cloudapp.azure.com
    path: /(.*)
```

Filedrop - values.yaml
```yaml
  deployment:
  ingress:
    name: file-drop-service-ingress
    port: 80 << change this port here
    host: file-drop-develop.uksouth.cloudapp.azure.com
    path: /(.*)
```
