### ISSUE TITLE
Incorrect GVK used when granting permissions to Ingress (Rancher deployment)

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#297]
_Reported by Rancher development team._
In the `cert-manager` there is a mismatch between the GVK of the `Ingress` resource referenced in the code and the permissions granted in the `(Cluster)Role`.

This is not reported as an issue in AKS deployments due to Rancher using Kubenetes v1.19 and AKS being at v1.18.

_Logged Error_
```
E0215 21:32:59.761372       1 reflector.go:127] external/io_k8s_client_go/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot list resource "ingresses" in API group "extensions" at the cluster scope
```

We need to make sure that permissions on the Ingress resource are granted using the `extensions/v1beta1` GVK.

To address this the advice is 
> Where selection of GVK is made based upon `.Capabilities.KubeVersion.GitVersion`, remove that check and fix the GVK to `extensions/v1beta1`
> For anything defining permissions, i.e. Roles  and ClusterRole , include permissions on both GVKs.

The following changes are required to the charts for the `adaptation`, `administration`, `filedrop` and `ncfs` namespaces
- Remove the `.Capabilities.KubeVersion.GitVersion` check and fix the GVK used in Ingress definition as `extensions/v1beta1` 
- Replace the use of `networking.k8s.io/v1beta1` by any `Ingress` with `extensions/v1beta1`
- Update all `Role` and `ClusterRole` definitions to assign permissions in both GVKs (`extensions/v1beta1` & `networking.k8s.io/v1beta1`)

**Comment by BigPeeg** [comment]
An example of assigning permissions to a `Role` or `ClusterRole` in both GVKs is shown below
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: someRole
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  [...]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  [...]
```
